services:
  apilayer:
    image: apilayer
    build:
      context: .
      dockerfile: ApiLayer/Dockerfile
      target: development
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/src
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1 
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - cinema-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=anhduc9A@5
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge

volumes:
  sqlvolume: