// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20260114094357_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.auditorium_info_entity", b =>
                {
                    b.Property<Guid>("auditoriumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("activeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("auditoriumNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("cinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("deletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("movieFormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("updatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("auditoriumId");

                    b.HasIndex("cinemaId");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("deletedByUserId");

                    b.HasIndex("movieFormatId");

                    b.HasIndex("updatedByUserId");

                    b.HasIndex("auditoriumNumber", "cinemaId")
                        .IsUnique()
                        .HasFilter("[isDeleted] = CAST(0 AS BIT)");

                    b.ToTable("auditorium_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.cinema_discount_info_entity", b =>
                {
                    b.Property<Guid>("cinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("movieFormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("activeAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("deletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("discountNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("discountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("updatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cinemaId", "movieFormatId");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("deletedByUserId");

                    b.HasIndex("movieFormatId");

                    b.HasIndex("updatedByUserId");

                    b.ToTable("cinema_discount_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.cinema_info_entity", b =>
                {
                    b.Property<Guid>("cinemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("activeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("cinemaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cinemaHotLineNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("cinemaLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cinemaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("deletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("managerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("updatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cinemaId");

                    b.HasIndex("cinemaHotLineNumber")
                        .IsUnique();

                    b.HasIndex("cinemaName")
                        .IsUnique()
                        .HasFilter("[isDeleted] = CAST(0 AS BIT)");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("deletedByUserId");

                    b.HasIndex("managerId");

                    b.HasIndex("updatedByUserId");

                    b.ToTable("cinema_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.cinema_surcharge_infos_entity", b =>
                {
                    b.Property<Guid>("cinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("movieFormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("activeAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("deletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("surchangePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("updatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("userSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("cinemaId", "movieFormatId");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("deletedByUserId");

                    b.HasIndex("updatedByUserId");

                    b.HasIndex("userSegmentId");

                    b.HasIndex("movieFormatId", "userSegmentId")
                        .IsUnique();

                    b.ToTable("cinema_surcharge_infos_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.seats_info_entity", b =>
                {
                    b.Property<string>("seatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("activeAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("auditoriumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("colIndex")
                        .HasColumnType("int");

                    b.Property<double>("coordX")
                        .HasColumnType("float");

                    b.Property<double>("coordY")
                        .HasColumnType("float");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("deletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("rowIndex")
                        .HasColumnType("int");

                    b.Property<string>("seatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("updatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("seatId");

                    b.HasIndex("auditoriumId");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("deletedByUserId");

                    b.HasIndex("updatedByUserId");

                    b.ToTable("seats_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_genre_info_entity", b =>
                {
                    b.Property<Guid>("movieGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("movieGenreDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("movieGenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("movieGenreId");

                    b.HasIndex("movieGenreDescription")
                        .IsUnique();

                    b.HasIndex("movieGenreName")
                        .IsUnique();

                    b.ToTable("movie_genre_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_genre_movie_info_entity", b =>
                {
                    b.Property<Guid>("movieGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("movieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("movieGenreId", "movieId");

                    b.HasIndex("movieId");

                    b.ToTable("movie_genre_movie_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_info_entity", b =>
                {
                    b.Property<Guid>("movieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("activeAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("deletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("endedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("managerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("movieDescription")
                        .IsRequired()
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("movieImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("movieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("movieRequiredAgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("movie_required_age_entitymovieRequiredAgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("updatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("movieId");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("deletedByUserId");

                    b.HasIndex("managerId");

                    b.HasIndex("movieDescription")
                        .IsUnique();

                    b.HasIndex("movieImageUrl")
                        .IsUnique();

                    b.HasIndex("movieName")
                        .IsUnique();

                    b.HasIndex("movie_required_age_entitymovieRequiredAgeId");

                    b.HasIndex("updatedByUserId");

                    b.ToTable("movie_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_required_age_entity", b =>
                {
                    b.Property<Guid>("movieRequiredAgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("movieRequiredAgeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("movieRequiredAgeSymbol")
                        .IsRequired()
                        .HasColumnType("nchar(10)");

                    b.HasKey("movieRequiredAgeId");

                    b.HasIndex("movieRequiredAgeDescription")
                        .IsUnique();

                    b.HasIndex("movieRequiredAgeSymbol")
                        .IsUnique();

                    b.ToTable("movie_required_age_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_schedule_info_entity", b =>
                {
                    b.Property<Guid>("movieScheduleInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("activeAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("auditoriumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("deletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("endedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("movieFormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("movieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("startedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("updatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("movieScheduleInfoId");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("deletedByUserId");

                    b.HasIndex("movieFormatId");

                    b.HasIndex("movieId");

                    b.HasIndex("updatedByUserId");

                    b.HasIndex("auditoriumId", "startedTime")
                        .IsUnique()
                        .HasFilter("[isDeleted] = 0");

                    b.ToTable("movie_schedule_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movies_Infos.movie_format_info_entity", b =>
                {
                    b.Property<Guid>("movieFormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("activeAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("createdByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("deletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("movieFormatDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("movieFormatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("movieFormatPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("updatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("movieFormatId");

                    b.HasIndex("createdByUserId");

                    b.HasIndex("deletedByUserId");

                    b.HasIndex("updatedByUserId");

                    b.ToTable("movie_format_info_entity");

                    b.HasData(
                        new
                        {
                            movieFormatId = new Guid("3fbc4a32-15f5-47e0-b98a-784f1b8a9612"),
                            activeAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            isActive = true,
                            isDeleted = false,
                            movieFormatDescription = "Standard digital 2D format with crystal clear image quality.",
                            movieFormatName = "2D",
                            movieFormatPrice = 80000m,
                            updatedAt = new DateTime(2026, 1, 14, 16, 43, 57, 377, DateTimeKind.Local).AddTicks(5671)
                        },
                        new
                        {
                            movieFormatId = new Guid("7a5e82b1-c4d3-4a92-9e11-3f4b52c1a8d9"),
                            activeAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            isActive = true,
                            isDeleted = false,
                            movieFormatDescription = "Immersive three-dimensional visual experience with specialized glasses.",
                            movieFormatName = "3D",
                            movieFormatPrice = 110000m,
                            updatedAt = new DateTime(2026, 1, 14, 16, 43, 57, 377, DateTimeKind.Local).AddTicks(5679)
                        },
                        new
                        {
                            movieFormatId = new Guid("d29b0f1c-8e2a-4c5b-bc3d-1a2f3e4d5c6b"),
                            activeAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            isActive = true,
                            isDeleted = false,
                            movieFormatDescription = "Giant screen format with unparalleled brightness and ultra-high resolution.",
                            movieFormatName = "IMAX",
                            movieFormatPrice = 250000m,
                            updatedAt = new DateTime(2026, 1, 14, 16, 43, 57, 377, DateTimeKind.Local).AddTicks(5682)
                        },
                        new
                        {
                            movieFormatId = new Guid("f9e1d2c3-b4a5-4e6f-8d7c-9b0a1f2e3d4c"),
                            activeAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            isActive = true,
                            isDeleted = false,
                            movieFormatDescription = "State-of-the-art surround sound technology for a lifelike audio experience.",
                            movieFormatName = "Dolby Atmos",
                            movieFormatPrice = 130000m,
                            updatedAt = new DateTime(2026, 1, 14, 16, 43, 57, 377, DateTimeKind.Local).AddTicks(5685)
                        },
                        new
                        {
                            movieFormatId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            activeAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            isActive = true,
                            isDeleted = false,
                            movieFormatDescription = "A revolutionary 270-degree panoramic cinematic experience.",
                            movieFormatName = "ScreenX",
                            movieFormatPrice = 160000m,
                            updatedAt = new DateTime(2026, 1, 14, 16, 43, 57, 377, DateTimeKind.Local).AddTicks(5687)
                        },
                        new
                        {
                            movieFormatId = new Guid("5d4c3b2a-1f0e-4d9c-8b7a-6e5d4c3b2a1f"),
                            activeAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            isActive = true,
                            isDeleted = false,
                            movieFormatDescription = "Multi-sensory experience featuring motion seats, wind, water, and scents.",
                            movieFormatName = "4DX",
                            movieFormatPrice = 180000m,
                            updatedAt = new DateTime(2026, 1, 14, 16, 43, 57, 377, DateTimeKind.Local).AddTicks(5690)
                        },
                        new
                        {
                            movieFormatId = new Guid("9f8e7d6c-5b4a-4e3d-2c1b-0a9f8e7d6c5b"),
                            activeAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            isActive = true,
                            isDeleted = false,
                            movieFormatDescription = "Premium luxury seating with in-theater dining and personalized service.",
                            movieFormatName = "Gold Class",
                            movieFormatPrice = 300000m,
                            updatedAt = new DateTime(2026, 1, 14, 16, 43, 57, 377, DateTimeKind.Local).AddTicks(5692)
                        },
                        new
                        {
                            movieFormatId = new Guid("1c2d3e4f-5a6b-4c7d-8e9f-0a1b2c3d4e5f"),
                            activeAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            isActive = true,
                            isDeleted = false,
                            movieFormatDescription = "Luxury bed-seating auditorium designed for ultimate comfort and couples.",
                            movieFormatName = "L'Amour",
                            movieFormatPrice = 600000m,
                            updatedAt = new DateTime(2026, 1, 14, 16, 43, 57, 377, DateTimeKind.Local).AddTicks(5694)
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.order_details_info", b =>
                {
                    b.Property<Guid>("orderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("movieScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("priceEach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("seatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("orderId", "movieScheduleId");

                    b.HasIndex("movieScheduleId");

                    b.ToTable("order_details_info");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.order_info_entity", b =>
                {
                    b.Property<Guid>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("customerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("customerEmail")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("orderStatus")
                        .HasColumnType("int");

                    b.Property<int>("paymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("totalQuantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("orderId");

                    b.HasIndex("userId", "orderId")
                        .IsUnique()
                        .HasFilter("[userId] IS NOT NULL");

                    b.ToTable("order_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.role_list_info_entity", b =>
                {
                    b.Property<Guid>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("roleId");

                    b.HasIndex("roleName")
                        .IsUnique();

                    b.ToTable("role_list_info_entity");

                    b.HasData(
                        new
                        {
                            roleId = new Guid("2b9c8d0e-f5a6-7b8c-d9e0-1f2a3b4c5d6e"),
                            roleName = "Customer"
                        },
                        new
                        {
                            roleId = new Guid("1a8f7b9c-d4e5-4f6a-b7c8-9d0e1f2a3b4c"),
                            roleName = "Cashier"
                        },
                        new
                        {
                            roleId = new Guid("3c0d9e1f-a6b7-c8d9-e0f1-2a3b4c5d6e7f"),
                            roleName = "Admin"
                        },
                        new
                        {
                            roleId = new Guid("4d1e0f2a-b7c8-d9e0-f1a2-3b4c5d6e7f8a"),
                            roleName = "MovieManager"
                        },
                        new
                        {
                            roleId = new Guid("5e2f1a3b-c8d9-e0f1-a2b3-4c5d6e7f8a9b"),
                            roleName = "TheaterManager"
                        },
                        new
                        {
                            roleId = new Guid("6f3a2b4c-d9e0-f1a2-b3c4-d5e6f7a8b9c0"),
                            roleName = "FacilitiesManager"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.user_info_entity", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("accoutStatus")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("refreshToken")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("registerMethod")
                        .HasColumnType("int");

                    b.Property<string>("subId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("userId");

                    b.HasIndex("refreshToken")
                        .IsUnique()
                        .HasFilter("[refreshToken] IS NOT NULL");

                    b.HasIndex("userEmail")
                        .IsUnique();

                    b.ToTable("user_info_entity");

                    b.HasData(
                        new
                        {
                            userId = new Guid("b2c3d4e5-f6a7-8b9c-d0e1-f2a3b4c5d6e7"),
                            accoutStatus = 0,
                            password = "$2a$12$ADqBiSquthm1g7bLZvg6UulJ5QJFQQ6olUQzf66AQfJDGbQ2W1wlG",
                            registerMethod = 0,
                            userEmail = "user@example.com"
                        },
                        new
                        {
                            userId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            accoutStatus = 0,
                            password = "$2a$12$91JfhncA5t3ssFtiaoKjSOrbMj7zON.wtL/n3cjme/wvK2kDCgZ7K",
                            registerMethod = 0,
                            userEmail = "admin@example.com"
                        },
                        new
                        {
                            userId = new Guid("7b5d2c1e-9f8a-3e7b-c1d2-a0e9f8c7b6a5"),
                            accoutStatus = 0,
                            password = "$2a$12$FeLXQjfW3gfNFfELxTJS3.gH8o9Y2CB5WSGcDZxKMrPEJiR2RcxIS",
                            registerMethod = 0,
                            userEmail = "theater@example.com"
                        },
                        new
                        {
                            userId = new Guid("f1a0e9b8-d7c6-5e4f-a3b2-1d0c9b8a7f6e"),
                            accoutStatus = 0,
                            password = "$2a$12$CkugZHMrWhxG0h6hUqOAf.fX9QQFkLnfnLlI.xWCNZ1y/PivtfN2O",
                            registerMethod = 0,
                            userEmail = "facilities@example.com"
                        },
                        new
                        {
                            userId = new Guid("a1b2c3d4-e5f6-7a8b-c9d0-e1f2a3b4c5d6"),
                            accoutStatus = 0,
                            password = "$2a$12$CkugZHMrWhxG0h6hUqOAf.fX9QQFkLnfnLlI.xWCNZ1y/PivtfN2O",
                            registerMethod = 0,
                            userEmail = "cashier@example.com"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.user_profile_entity", b =>
                {
                    b.Property<Guid>("userID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("identityCode")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("userID");

                    b.HasIndex("identityCode")
                        .IsUnique();

                    b.HasIndex("phoneNumber")
                        .IsUnique();

                    b.ToTable("user_profile_entity");

                    b.HasData(
                        new
                        {
                            userID = new Guid("b2c3d4e5-f6a7-8b9c-d0e1-f2a3b4c5d6e7"),
                            dateOfBirth = new DateTime(2005, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            identityCode = "NjItl/uAfIOjjzvtWPbnzg==",
                            phoneNumber = "0123456789",
                            userName = "Movie Manager 1"
                        },
                        new
                        {
                            userID = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            dateOfBirth = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            identityCode = "pxc5zG8sfEcsJrHg1AjV3w==",
                            phoneNumber = "0988123456",
                            userName = "Admin"
                        },
                        new
                        {
                            userID = new Guid("7b5d2c1e-9f8a-3e7b-c1d2-a0e9f8c7b6a5"),
                            dateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            identityCode = "Pk3VcB5Kk2xdhHerF74zBg==",
                            phoneNumber = "0977234567",
                            userName = "Theater Manager"
                        },
                        new
                        {
                            userID = new Guid("f1a0e9b8-d7c6-5e4f-a3b2-1d0c9b8a7f6e"),
                            dateOfBirth = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            identityCode = "cFobMOQzli9Um8tWi/vJZg==",
                            phoneNumber = "0966345678",
                            userName = "Facilities Manager"
                        },
                        new
                        {
                            userID = new Guid("a1b2c3d4-e5f6-7a8b-c9d0-e1f2a3b4c5d6"),
                            dateOfBirth = new DateTime(1995, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            identityCode = "pFoBRlv4RT1kyqKE1Ch3Hw==",
                            phoneNumber = "0944456789",
                            userName = "Cashier"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.user_role_info_entity", b =>
                {
                    b.Property<Guid>("roleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("roleId", "userId");

                    b.HasIndex("userId");

                    b.ToTable("user_role_info_entity");

                    b.HasData(
                        new
                        {
                            roleId = new Guid("3c0d9e1f-a6b7-c8d9-e0f1-2a3b4c5d6e7f"),
                            userId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c")
                        },
                        new
                        {
                            roleId = new Guid("4d1e0f2a-b7c8-d9e0-f1a2-3b4c5d6e7f8a"),
                            userId = new Guid("b2c3d4e5-f6a7-8b9c-d0e1-f2a3b4c5d6e7")
                        },
                        new
                        {
                            roleId = new Guid("5e2f1a3b-c8d9-e0f1-a2b3-4c5d6e7f8a9b"),
                            userId = new Guid("7b5d2c1e-9f8a-3e7b-c1d2-a0e9f8c7b6a5")
                        },
                        new
                        {
                            roleId = new Guid("6f3a2b4c-d9e0-f1a2-b3c4-d5e6f7a8b9c0"),
                            userId = new Guid("f1a0e9b8-d7c6-5e4f-a3b2-1d0c9b8a7f6e")
                        },
                        new
                        {
                            roleId = new Guid("1a8f7b9c-d4e5-4f6a-b7c8-9d0e1f2a3b4c"),
                            userId = new Guid("a1b2c3d4-e5f6-7a8b-c9d0-e1f2a3b4c5d6")
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.user_segments_info_entity", b =>
                {
                    b.Property<Guid>("userSegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("userSegmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("userSegmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("userSegmentId");

                    b.HasIndex("userSegmentDescription")
                        .IsUnique();

                    b.HasIndex("userSegmentName")
                        .IsUnique();

                    b.ToTable("user_segments_info_entity");

                    b.HasData(
                        new
                        {
                            userSegmentId = new Guid("7b2e1a9d-3f5c-4e8b-91d2-a6b3c4d5e6f7"),
                            userSegmentDescription = "Standard customers aged 18 to 59.",
                            userSegmentName = "Adult"
                        },
                        new
                        {
                            userSegmentId = new Guid("1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d"),
                            userSegmentDescription = "Full-time students with a valid student ID card.",
                            userSegmentName = "Student"
                        },
                        new
                        {
                            userSegmentId = new Guid("9f8e7d6c-5b4a-4e3d-2c1b-0a9f8e7d6c5b"),
                            userSegmentDescription = "Children under 12 years old or under 1.3m in height.",
                            userSegmentName = "Child"
                        },
                        new
                        {
                            userSegmentId = new Guid("3d4e5f6a-7b8c-4d9e-0f1a-2b3c4d5e6f7a"),
                            userSegmentDescription = "Senior citizens aged 60 and above with a valid ID.",
                            userSegmentName = "Senior"
                        },
                        new
                        {
                            userSegmentId = new Guid("5c6d7e8f-9a0b-4c1d-2e3f-4a5b6c7d8e9f"),
                            userSegmentDescription = "Registered members with basic loyalty benefits.",
                            userSegmentName = "Standard Member"
                        },
                        new
                        {
                            userSegmentId = new Guid("d1e2f3a4-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            userSegmentDescription = "High-tier members with premium discounts and exclusive offers.",
                            userSegmentName = "VIP Member"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Vouchers.voucher_info_entity", b =>
                {
                    b.Property<Guid>("voucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("voucherAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("voucherDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("voucherDiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("voucherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("voucherId");

                    b.HasIndex("roleId");

                    b.HasIndex("voucherDescription")
                        .IsUnique();

                    b.HasIndex("voucherName")
                        .IsUnique();

                    b.ToTable("voucher_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.auditorium_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.Cinema_Infos.cinema_info_entity", "cinema_info_entity")
                        .WithMany("auditorium_info_entity")
                        .HasForeignKey("cinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "creator")
                        .WithMany("createdAuditoriums")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "deleter")
                        .WithMany("deletedAuditoriums")
                        .HasForeignKey("deletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.Movies_Infos.movie_format_info_entity", "movie_format_info_entity")
                        .WithMany()
                        .HasForeignKey("movieFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "updater")
                        .WithMany("updatedAuditoriums")
                        .HasForeignKey("updatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("cinema_info_entity");

                    b.Navigation("creator");

                    b.Navigation("deleter");

                    b.Navigation("movie_format_info_entity");

                    b.Navigation("updater");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.cinema_discount_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.Cinema_Infos.cinema_info_entity", "cinema_info_entity")
                        .WithMany("cinema_discount_info_entity")
                        .HasForeignKey("cinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "creator")
                        .WithMany("createdCinemaDiscounts")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "deleter")
                        .WithMany("deletedCinemaDiscounts")
                        .HasForeignKey("deletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.Movies_Infos.movie_format_info_entity", "movie_format_info_entity")
                        .WithMany("cinema_discount_info_entity")
                        .HasForeignKey("movieFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "updater")
                        .WithMany("updatedCinemaDiscounts")
                        .HasForeignKey("updatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("cinema_info_entity");

                    b.Navigation("creator");

                    b.Navigation("deleter");

                    b.Navigation("movie_format_info_entity");

                    b.Navigation("updater");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.cinema_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "creator")
                        .WithMany("createdCinemas")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "deleter")
                        .WithMany("deletedCinemas")
                        .HasForeignKey("deletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "manager")
                        .WithMany("managedCinemas")
                        .HasForeignKey("managerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "updater")
                        .WithMany("updatedCinemas")
                        .HasForeignKey("updatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("creator");

                    b.Navigation("deleter");

                    b.Navigation("manager");

                    b.Navigation("updater");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.cinema_surcharge_infos_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.Cinema_Infos.cinema_info_entity", "cinema_info_entity")
                        .WithMany("cinema_surcharge_infos_entity")
                        .HasForeignKey("cinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "creator")
                        .WithMany("createdCinemaSurchargeInfos")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "deleter")
                        .WithMany("deleteCinemaSurchargeInfos")
                        .HasForeignKey("deletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.Movies_Infos.movie_format_info_entity", "movie_format_info_entity")
                        .WithMany("cinema_surcharge_infos_entity")
                        .HasForeignKey("movieFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "updater")
                        .WithMany("updatedCinemaSurchargeInfos")
                        .HasForeignKey("updatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.User_Info.user_segments_info_entity", "user_segments_info_entity")
                        .WithMany("cinema_surcharge_infos_entity")
                        .HasForeignKey("userSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cinema_info_entity");

                    b.Navigation("creator");

                    b.Navigation("deleter");

                    b.Navigation("movie_format_info_entity");

                    b.Navigation("updater");

                    b.Navigation("user_segments_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.seats_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.Cinema_Infos.auditorium_info_entity", "auditorium_info_entity")
                        .WithMany("seats_info_entity")
                        .HasForeignKey("auditoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "creator")
                        .WithMany("createdSeats")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "deleter")
                        .WithMany("deletedSeats")
                        .HasForeignKey("deletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "updater")
                        .WithMany("updatedSeats")
                        .HasForeignKey("updatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("auditorium_info_entity");

                    b.Navigation("creator");

                    b.Navigation("deleter");

                    b.Navigation("updater");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_genre_movie_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.Movie_infos.movie_genre_info_entity", "movie_genre_info_entity")
                        .WithMany("movie_genre_movie_info_entity")
                        .HasForeignKey("movieGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Movie_infos.movie_info_entity", "movie_info_entity")
                        .WithMany("movie_genre_movie_info_entity")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie_genre_info_entity");

                    b.Navigation("movie_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "creator")
                        .WithMany("createdMovieInfos")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "deleter")
                        .WithMany("deletedMovieInfos")
                        .HasForeignKey("deletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "manager")
                        .WithMany()
                        .HasForeignKey("managerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Movie_infos.movie_required_age_entity", "movie_required_age_entity")
                        .WithMany("movie_info_entity")
                        .HasForeignKey("movie_required_age_entitymovieRequiredAgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "updater")
                        .WithMany("updatedMovieInfos")
                        .HasForeignKey("updatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("creator");

                    b.Navigation("deleter");

                    b.Navigation("manager");

                    b.Navigation("movie_required_age_entity");

                    b.Navigation("updater");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_schedule_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.Cinema_Infos.auditorium_info_entity", "auditorium_info_entity")
                        .WithMany("movie_schedule_info_entity")
                        .HasForeignKey("auditoriumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "creator")
                        .WithMany("createdSchedules")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "deleter")
                        .WithMany("deletedSchedules")
                        .HasForeignKey("deletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.Movies_Infos.movie_format_info_entity", "movie_format_info_entity")
                        .WithMany("movie_schedule_info_entity")
                        .HasForeignKey("movieFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Movie_infos.movie_info_entity", "movie_info_entity")
                        .WithMany("movie_schedule_info_entity")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "updater")
                        .WithMany("updatedSchedules")
                        .HasForeignKey("updatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("auditorium_info_entity");

                    b.Navigation("creator");

                    b.Navigation("deleter");

                    b.Navigation("movie_format_info_entity");

                    b.Navigation("movie_info_entity");

                    b.Navigation("updater");
                });

            modelBuilder.Entity("DataAccess.Entities.Movies_Infos.movie_format_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "creator")
                        .WithMany("createdMovieFormats")
                        .HasForeignKey("createdByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "deleter")
                        .WithMany("deletedMovieFormats")
                        .HasForeignKey("deletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "updater")
                        .WithMany("updatedMovieFormats")
                        .HasForeignKey("updatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("creator");

                    b.Navigation("deleter");

                    b.Navigation("updater");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.order_details_info", b =>
                {
                    b.HasOne("DataAccess.Entities.Movie_infos.movie_schedule_info_entity", "movie_schedule_info")
                        .WithMany("order_details_infos")
                        .HasForeignKey("movieScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.order_info_entity", "order_info")
                        .WithMany("order_details_info")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("movie_schedule_info");

                    b.Navigation("order_info");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.order_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "user_info")
                        .WithMany("order_info_entity")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user_info");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.user_profile_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "user_info_entity")
                        .WithOne("user_profile_entity")
                        .HasForeignKey("DataAccess.Entities.User_Info.user_profile_entity", "userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.user_role_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.User_Info.role_list_info_entity", "role_list_info_entity")
                        .WithMany("user_role_info_entity")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User_Info.user_info_entity", "user_info_entity")
                        .WithMany("user_role_info_entity")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role_list_info_entity");

                    b.Navigation("user_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Vouchers.voucher_info_entity", b =>
                {
                    b.HasOne("DataAccess.Entities.User_Info.role_list_info_entity", "role_list_info_entity")
                        .WithMany("voucher_info_entity")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role_list_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.auditorium_info_entity", b =>
                {
                    b.Navigation("movie_schedule_info_entity");

                    b.Navigation("seats_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Cinema_Infos.cinema_info_entity", b =>
                {
                    b.Navigation("auditorium_info_entity");

                    b.Navigation("cinema_discount_info_entity");

                    b.Navigation("cinema_surcharge_infos_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_genre_info_entity", b =>
                {
                    b.Navigation("movie_genre_movie_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_info_entity", b =>
                {
                    b.Navigation("movie_genre_movie_info_entity");

                    b.Navigation("movie_schedule_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_required_age_entity", b =>
                {
                    b.Navigation("movie_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.Movie_infos.movie_schedule_info_entity", b =>
                {
                    b.Navigation("order_details_infos");
                });

            modelBuilder.Entity("DataAccess.Entities.Movies_Infos.movie_format_info_entity", b =>
                {
                    b.Navigation("cinema_discount_info_entity");

                    b.Navigation("cinema_surcharge_infos_entity");

                    b.Navigation("movie_schedule_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.order_info_entity", b =>
                {
                    b.Navigation("order_details_info");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.role_list_info_entity", b =>
                {
                    b.Navigation("user_role_info_entity");

                    b.Navigation("voucher_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.user_info_entity", b =>
                {
                    b.Navigation("createdAuditoriums");

                    b.Navigation("createdCinemaDiscounts");

                    b.Navigation("createdCinemaSurchargeInfos");

                    b.Navigation("createdCinemas");

                    b.Navigation("createdMovieFormats");

                    b.Navigation("createdMovieInfos");

                    b.Navigation("createdSchedules");

                    b.Navigation("createdSeats");

                    b.Navigation("deleteCinemaSurchargeInfos");

                    b.Navigation("deletedAuditoriums");

                    b.Navigation("deletedCinemaDiscounts");

                    b.Navigation("deletedCinemas");

                    b.Navigation("deletedMovieFormats");

                    b.Navigation("deletedMovieInfos");

                    b.Navigation("deletedSchedules");

                    b.Navigation("deletedSeats");

                    b.Navigation("managedCinemas");

                    b.Navigation("order_info_entity");

                    b.Navigation("updatedAuditoriums");

                    b.Navigation("updatedCinemaDiscounts");

                    b.Navigation("updatedCinemaSurchargeInfos");

                    b.Navigation("updatedCinemas");

                    b.Navigation("updatedMovieFormats");

                    b.Navigation("updatedMovieInfos");

                    b.Navigation("updatedSchedules");

                    b.Navigation("updatedSeats");

                    b.Navigation("user_profile_entity")
                        .IsRequired();

                    b.Navigation("user_role_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.User_Info.user_segments_info_entity", b =>
                {
                    b.Navigation("cinema_surcharge_infos_entity");
                });
#pragma warning restore 612, 618
        }
    }
}
