// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.AuditoriumInfoEntities", b =>
                {
                    b.Property<Guid>("AuditoriumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditoriumNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MovieFormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditoriumId");

                    b.HasIndex("CinemaId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("MovieFormatId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("AuditoriumNumber", "CinemaId")
                        .IsUnique()
                        .HasFilter("[isDeleted] = CAST(0 AS BIT)");

                    b.ToTable("AuditoriumInfoEntities", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.CinemaDiscountInfoEntity", b =>
                {
                    b.Property<Guid>("CinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieFormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiscountNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CinemaId", "MovieFormatId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("MovieFormatId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("CinemaDiscountInfoEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.CinemaInfoEntity", b =>
                {
                    b.Property<Guid>("CinemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CinemaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CinemaHotLineNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("CinemaLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CinemaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CinemaId");

                    b.HasIndex("CinemaHotLineNumber")
                        .IsUnique();

                    b.HasIndex("CinemaName")
                        .IsUnique()
                        .HasFilter("[isDeleted] = CAST(0 AS BIT)");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("CinemaInfoEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.CinemaSurchargeInfosEntity", b =>
                {
                    b.Property<Guid>("CinemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieFormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("SurchangePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CinemaId", "MovieFormatId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UserSegmentId");

                    b.HasIndex("MovieFormatId", "UserSegmentId")
                        .IsUnique();

                    b.ToTable("CinemaSurchargeInfosEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.SeatsInfoEntity", b =>
                {
                    b.Property<string>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ColIndex")
                        .HasColumnType("int");

                    b.Property<double>("CoordX")
                        .HasColumnType("float");

                    b.Property<double>("CoordY")
                        .HasColumnType("float");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SeatId");

                    b.HasIndex("AuditoriumId");

                    b.ToTable("SeatsInfoEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieFormatInfoEntity", b =>
                {
                    b.Property<Guid>("MovieFormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MovieFormatDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MovieFormatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MovieFormatPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieFormatId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("MovieFormatInfoEntity", (string)null);

                    b.HasData(
                        new
                        {
                            MovieFormatId = new Guid("3fbc4a32-15f5-47e0-b98a-784f1b8a9612"),
                            ActiveAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            IsActive = true,
                            IsDeleted = false,
                            MovieFormatDescription = "Standard digital 2D format with crystal clear image quality.",
                            MovieFormatName = "2D",
                            MovieFormatPrice = 80000m,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 31, 23, 126, DateTimeKind.Local).AddTicks(1798)
                        },
                        new
                        {
                            MovieFormatId = new Guid("7a5e82b1-c4d3-4a92-9e11-3f4b52c1a8d9"),
                            ActiveAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            IsActive = true,
                            IsDeleted = false,
                            MovieFormatDescription = "Immersive three-dimensional visual experience with specialized glasses.",
                            MovieFormatName = "3D",
                            MovieFormatPrice = 110000m,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 31, 23, 126, DateTimeKind.Local).AddTicks(1806)
                        },
                        new
                        {
                            MovieFormatId = new Guid("d29b0f1c-8e2a-4c5b-bc3d-1a2f3e4d5c6b"),
                            ActiveAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            IsActive = true,
                            IsDeleted = false,
                            MovieFormatDescription = "Giant screen format with unparalleled brightness and ultra-high resolution.",
                            MovieFormatName = "IMAX",
                            MovieFormatPrice = 250000m,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 31, 23, 126, DateTimeKind.Local).AddTicks(1809)
                        },
                        new
                        {
                            MovieFormatId = new Guid("f9e1d2c3-b4a5-4e6f-8d7c-9b0a1f2e3d4c"),
                            ActiveAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            IsActive = true,
                            IsDeleted = false,
                            MovieFormatDescription = "State-of-the-art surround sound technology for a lifelike audio experience.",
                            MovieFormatName = "Dolby Atmos",
                            MovieFormatPrice = 130000m,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 31, 23, 126, DateTimeKind.Local).AddTicks(1812)
                        },
                        new
                        {
                            MovieFormatId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            ActiveAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            IsActive = true,
                            IsDeleted = false,
                            MovieFormatDescription = "A revolutionary 270-degree panoramic cinematic experience.",
                            MovieFormatName = "ScreenX",
                            MovieFormatPrice = 160000m,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 31, 23, 126, DateTimeKind.Local).AddTicks(1814)
                        },
                        new
                        {
                            MovieFormatId = new Guid("5d4c3b2a-1f0e-4d9c-8b7a-6e5d4c3b2a1f"),
                            ActiveAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            IsActive = true,
                            IsDeleted = false,
                            MovieFormatDescription = "Multi-sensory experience featuring motion seats, wind, water, and scents.",
                            MovieFormatName = "4DX",
                            MovieFormatPrice = 180000m,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 31, 23, 126, DateTimeKind.Local).AddTicks(1818)
                        },
                        new
                        {
                            MovieFormatId = new Guid("9f8e7d6c-5b4a-4e3d-2c1b-0a9f8e7d6c5b"),
                            ActiveAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            IsActive = true,
                            IsDeleted = false,
                            MovieFormatDescription = "Premium luxury seating with in-theater dining and personalized service.",
                            MovieFormatName = "Gold Class",
                            MovieFormatPrice = 300000m,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 31, 23, 126, DateTimeKind.Local).AddTicks(1867)
                        },
                        new
                        {
                            MovieFormatId = new Guid("1c2d3e4f-5a6b-4c7d-8e9f-0a1b2c3d4e5f"),
                            ActiveAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            IsActive = true,
                            IsDeleted = false,
                            MovieFormatDescription = "Luxury bed-seating auditorium designed for ultimate comfort and couples.",
                            MovieFormatName = "L'Amour",
                            MovieFormatPrice = 600000m,
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 31, 23, 126, DateTimeKind.Local).AddTicks(1869)
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieGenreInfoEntity", b =>
                {
                    b.Property<Guid>("MovieGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MovieGenreDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MovieGenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MovieGenreId");

                    b.HasIndex("MovieGenreDescription")
                        .IsUnique();

                    b.HasIndex("MovieGenreName")
                        .IsUnique();

                    b.ToTable("MovieGenreInfoEntity", (string)null);

                    b.HasData(
                        new
                        {
                            MovieGenreId = new Guid("f2a1b3c4-d5e6-4f7a-8b9c-0d1e2f3a4b5c"),
                            MovieGenreDescription = "Fast-paced movies with physical feats, stunts, and heroic battles.",
                            MovieGenreName = "Action"
                        },
                        new
                        {
                            MovieGenreId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            MovieGenreDescription = "Films designed to entertain and provoke laughter through humor.",
                            MovieGenreName = "Comedy"
                        },
                        new
                        {
                            MovieGenreId = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            MovieGenreDescription = "Focuses on realistic characters and emotional themes of human conflict.",
                            MovieGenreName = "Drama"
                        },
                        new
                        {
                            MovieGenreId = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            MovieGenreDescription = "Intended to scare, shock, and thrill audiences with supernatural or dark themes.",
                            MovieGenreName = "Horror"
                        },
                        new
                        {
                            MovieGenreId = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            MovieGenreDescription = "Exploring futuristic concepts, space travel, and advanced technology.",
                            MovieGenreName = "Sci-Fi"
                        },
                        new
                        {
                            MovieGenreId = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            MovieGenreDescription = "Focuses on romantic love relationships and emotional connections.",
                            MovieGenreName = "Romance"
                        },
                        new
                        {
                            MovieGenreId = new Guid("f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c"),
                            MovieGenreDescription = "Feature films produced using traditional or computer-generated imagery.",
                            MovieGenreName = "Animation"
                        },
                        new
                        {
                            MovieGenreId = new Guid("0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            MovieGenreDescription = "Non-fictional films intended to document reality for instruction or history.",
                            MovieGenreName = "Documentary"
                        },
                        new
                        {
                            MovieGenreId = new Guid("1b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            MovieGenreDescription = "Movies characterized by excitement, suspense, and intense anticipation.",
                            MovieGenreName = "Thriller"
                        },
                        new
                        {
                            MovieGenreId = new Guid("2c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            MovieGenreDescription = "Exciting journeys to new places, often involving a quest or exploration.",
                            MovieGenreName = "Adventure"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieGenreMovieInfoEntity", b =>
                {
                    b.Property<Guid>("MovieGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieGenreId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGenreMovieInfoEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieInfoEntity", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MovieDescription")
                        .IsRequired()
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("MovieImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MovieRequiredAgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("MovieDescription")
                        .IsUnique();

                    b.HasIndex("MovieImageUrl")
                        .IsUnique();

                    b.HasIndex("MovieName")
                        .IsUnique();

                    b.HasIndex("MovieRequiredAgeId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("MovieInfoEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieScheduleInfoEntity", b =>
                {
                    b.Property<Guid>("MovieScheduleInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MovieFormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieScheduleInfoId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("MovieFormatId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("AuditoriumId", "StartedTime")
                        .IsUnique()
                        .HasFilter("[isDeleted] = 0");

                    b.ToTable("MovieScheduleInfoEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.movieFormatMovieInfoEntity", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId", "FormatId");

                    b.HasIndex("FormatId");

                    b.ToTable("MovieFormatMovieInfoEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.movieRequiredAgeEntity", b =>
                {
                    b.Property<Guid>("MovieRequiredAgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MovieRequiredAgeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MovieRequiredAgeSymbol")
                        .IsRequired()
                        .HasColumnType("nchar(10)");

                    b.HasKey("MovieRequiredAgeId");

                    b.HasIndex("MovieRequiredAgeDescription")
                        .IsUnique();

                    b.HasIndex("MovieRequiredAgeSymbol")
                        .IsUnique();

                    b.ToTable("MovieRequiredAgeEntity", (string)null);

                    b.HasData(
                        new
                        {
                            MovieRequiredAgeId = new Guid("7a2f4b1d-9c3e-4d5a-8b2c-6f1e0a9d4b5c"),
                            MovieRequiredAgeDescription = "General Admission: Suitable for audiences of all ages.",
                            MovieRequiredAgeSymbol = "P"
                        },
                        new
                        {
                            MovieRequiredAgeId = new Guid("3d8e9a2b-1f0c-4b5a-9d6e-7f2a1b4c3d0e"),
                            MovieRequiredAgeDescription = "Parental Guidance: Films suitable for children under 13 with parental supervision.",
                            MovieRequiredAgeSymbol = "K"
                        },
                        new
                        {
                            MovieRequiredAgeId = new Guid("5c1b2d4e-8a9b-4c0d-7f6e-1d2c3b4a5e0f"),
                            MovieRequiredAgeDescription = "13+: This film is restricted to audiences aged 13 and above.",
                            MovieRequiredAgeSymbol = "T13"
                        },
                        new
                        {
                            MovieRequiredAgeId = new Guid("9f0e1d2c-3b4a-4d5e-6f7a-8b9c0d1e2f3a"),
                            MovieRequiredAgeDescription = "16+: This film is restricted to audiences aged 16 and above.",
                            MovieRequiredAgeSymbol = "T16"
                        },
                        new
                        {
                            MovieRequiredAgeId = new Guid("2b3c4d5e-6f7a-4b8c-9d0e-1f2a3b4c5d6e"),
                            MovieRequiredAgeDescription = "18+: Adult only. This film is restricted to audiences aged 18 and above.",
                            MovieRequiredAgeSymbol = "T18"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.OrderDetailsInfo", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceEach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId", "MovieScheduleId");

                    b.HasIndex("MovieScheduleId");

                    b.ToTable("OrderDetailsInfo", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.OrderInfoEntity", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId", "OrderId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("OrderInfoEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.RoleListInfoEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("RoleListInfoEntity", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("2b9c8d0e-f5a6-7b8c-d9e0-1f2a3b4c5d6e"),
                            RoleName = "Customer"
                        },
                        new
                        {
                            RoleId = new Guid("1a8f7b9c-d4e5-4f6a-b7c8-9d0e1f2a3b4c"),
                            RoleName = "Cashier"
                        },
                        new
                        {
                            RoleId = new Guid("3c0d9e1f-a6b7-c8d9-e0f1-2a3b4c5d6e7f"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("4d1e0f2a-b7c8-d9e0-f1a2-3b4c5d6e7f8a"),
                            RoleName = "MovieManager"
                        },
                        new
                        {
                            RoleId = new Guid("5e2f1a3b-c8d9-e0f1-a2b3-4c5d6e7f8a9b"),
                            RoleName = "TheaterManager"
                        },
                        new
                        {
                            RoleId = new Guid("6f3a2b4c-d9e0-f1a2-b3c4-d5e6f7a8b9c0"),
                            RoleName = "FacilitiesManager"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.UserInfoEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RegisterMethod")
                        .HasColumnType("int");

                    b.Property<string>("SubId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RefreshToken")
                        .IsUnique()
                        .HasFilter("[RefreshToken] IS NOT NULL");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("UserInfoEntity", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            AccountStatus = 0,
                            Password = "$2a$12$ufIKVZZwGlxHfQ0WSZQRmeDDeCuneaflIghQhHC6RupR0LVYLU5bi",
                            RegisterMethod = 0,
                            UserEmail = "admin@cinema.com"
                        },
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a7-8b9c-d0e1-f2a3b4c5d6e7"),
                            AccountStatus = 0,
                            Password = "$2a$12$FhmQsQjdtTZIHEzJIpAjZumRH0WvleZ2xidk22wSd841kxaQNE7ke",
                            RegisterMethod = 0,
                            UserEmail = "moviemanager@cinema.com"
                        },
                        new
                        {
                            UserId = new Guid("7b5d2c1e-9f8a-3e7b-c1d2-a0e9f8c7b6a5"),
                            AccountStatus = 0,
                            Password = "$2a$12$Lcz0doBD1.jofXcNDWF8x.4TSmUsyJKR/pbdP.fIh4Fc9yDV5X39m",
                            RegisterMethod = 0,
                            UserEmail = "theater@cinema.com"
                        },
                        new
                        {
                            UserId = new Guid("f1a0e9b8-d7c6-5e4f-a3b2-1d0c9b8a7f6e"),
                            AccountStatus = 0,
                            Password = "$2a$12$v2nSRwPmr62wHUakVl6TCeZLPGLEaVJBqotgF3qXVff0KnlWNWHE2",
                            RegisterMethod = 0,
                            UserEmail = "facilities@cinema.com"
                        },
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-c9d0-e1f2a3b4c5d6"),
                            AccountStatus = 0,
                            Password = "$2a$12$HSYdRT84AjbFawIfnmluJ.AMrBqmqBtKyyn6kNZFTNW7olAMMgXPy",
                            RegisterMethod = 0,
                            UserEmail = "cashier@cinema.com"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.UserProfileEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityCode")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("IdentityCode")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("UserProfileEntity", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c"),
                            DateOfBirth = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityCode = "NjItl/uAfIOjjzvtWPbnzg==",
                            PhoneNumber = "0988123456",
                            UserName = "System Administrator"
                        },
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a7-8b9c-d0e1-f2a3b4c5d6e7"),
                            DateOfBirth = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityCode = "pxc5zG8sfEcsJrHg1AjV3w==",
                            PhoneNumber = "0911111111",
                            UserName = "Movie Content Manager"
                        },
                        new
                        {
                            UserId = new Guid("7b5d2c1e-9f8a-3e7b-c1d2-a0e9f8c7b6a5"),
                            DateOfBirth = new DateTime(1988, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityCode = "Pk3VcB5Kk2xdhHerF74zBg==",
                            PhoneNumber = "0922222222",
                            UserName = "Cinema Operations Manager"
                        },
                        new
                        {
                            UserId = new Guid("f1a0e9b8-d7c6-5e4f-a3b2-1d0c9b8a7f6e"),
                            DateOfBirth = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityCode = "cFobMOQzli9Um8tWi/vJZg==",
                            PhoneNumber = "0933333333",
                            UserName = "Technical Facilities Manager"
                        },
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-c9d0-e1f2a3b4c5d6"),
                            DateOfBirth = new DateTime(1995, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentityCode = "pFoBRlv4RT1kyqKE1Ch3Hw==",
                            PhoneNumber = "0944444444",
                            UserName = "Main Cashier"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.UserRoleInfoEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleInfoEntity", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("3c0d9e1f-a6b7-c8d9-e0f1-2a3b4c5d6e7f"),
                            UserId = new Guid("e4e1f7d8-c3b2-4a90-8c67-2f5a1b3d9e0c")
                        },
                        new
                        {
                            RoleId = new Guid("4d1e0f2a-b7c8-d9e0-f1a2-3b4c5d6e7f8a"),
                            UserId = new Guid("b2c3d4e5-f6a7-8b9c-d0e1-f2a3b4c5d6e7")
                        },
                        new
                        {
                            RoleId = new Guid("5e2f1a3b-c8d9-e0f1-a2b3-4c5d6e7f8a9b"),
                            UserId = new Guid("7b5d2c1e-9f8a-3e7b-c1d2-a0e9f8c7b6a5")
                        },
                        new
                        {
                            RoleId = new Guid("6f3a2b4c-d9e0-f1a2-b3c4-d5e6f7a8b9c0"),
                            UserId = new Guid("f1a0e9b8-d7c6-5e4f-a3b2-1d0c9b8a7f6e")
                        },
                        new
                        {
                            RoleId = new Guid("1a8f7b9c-d4e5-4f6a-b7c8-9d0e1f2a3b4c"),
                            UserId = new Guid("a1b2c3d4-e5f6-7a8b-c9d0-e1f2a3b4c5d6")
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.UserSegmentsInfoEntity", b =>
                {
                    b.Property<Guid>("UserSegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserSegmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserSegmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserSegmentId");

                    b.HasIndex("UserSegmentDescription")
                        .IsUnique();

                    b.HasIndex("UserSegmentName")
                        .IsUnique();

                    b.ToTable("UserSegmentsInfoEntity", (string)null);

                    b.HasData(
                        new
                        {
                            UserSegmentId = new Guid("7b2e1a9d-3f5c-4e8b-91d2-a6b3c4d5e6f7"),
                            UserSegmentDescription = "Standard customers aged 18 to 59.",
                            UserSegmentName = "Adult"
                        },
                        new
                        {
                            UserSegmentId = new Guid("1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d"),
                            UserSegmentDescription = "Full-time students with a valid student ID card.",
                            UserSegmentName = "Student"
                        },
                        new
                        {
                            UserSegmentId = new Guid("9f8e7d6c-5b4a-4e3d-2c1b-0a9f8e7d6c5b"),
                            UserSegmentDescription = "Children under 12 years old or under 1.3m in height.",
                            UserSegmentName = "Child"
                        },
                        new
                        {
                            UserSegmentId = new Guid("3d4e5f6a-7b8c-4d9e-0f1a-2b3c4d5e6f7a"),
                            UserSegmentDescription = "Senior citizens aged 60 and above with a valid ID.",
                            UserSegmentName = "Senior"
                        },
                        new
                        {
                            UserSegmentId = new Guid("5c6d7e8f-9a0b-4c1d-2e3f-4a5b6c7d8e9f"),
                            UserSegmentDescription = "Registered members with basic loyalty benefits.",
                            UserSegmentName = "Standard Member"
                        },
                        new
                        {
                            UserSegmentId = new Guid("d1e2f3a4-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            UserSegmentDescription = "High-tier members with premium discounts and exclusive offers.",
                            UserSegmentName = "VIP Member"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Vouchers.VoucherInfoEntity", b =>
                {
                    b.Property<Guid>("voucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("voucherAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("voucherDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("voucherDiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("voucherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("voucherId");

                    b.HasIndex("roleId");

                    b.HasIndex("voucherDescription")
                        .IsUnique();

                    b.HasIndex("voucherName")
                        .IsUnique();

                    b.ToTable("VoucherInfoEntity", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.AuditoriumInfoEntities", b =>
                {
                    b.HasOne("DataAccess.Entities.CinemaInfos.CinemaInfoEntity", "CinemaInfoEntity")
                        .WithMany("AuditoriumInfoEntities")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Creator")
                        .WithMany("CreatedAuditoriums")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Deleter")
                        .WithMany("DeletedAuditoriums")
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.MovieInfos.MovieFormatInfoEntity", "MovieFormatInfoEntity")
                        .WithMany("auditorium_info_entities")
                        .HasForeignKey("MovieFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Updater")
                        .WithMany("UpdatedAuditoriums")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CinemaInfoEntity");

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("MovieFormatInfoEntity");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.CinemaDiscountInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.CinemaInfos.CinemaInfoEntity", "CinemaInfoEntity")
                        .WithMany("CinemaDiscountInfoEntity")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Creator")
                        .WithMany("CreatedCinemaDiscounts")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Deleter")
                        .WithMany("DeletedCinemaDiscounts")
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.MovieInfos.MovieFormatInfoEntity", "MovieFormatInfoEntity")
                        .WithMany("cinema_discount_info_entities")
                        .HasForeignKey("MovieFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Updater")
                        .WithMany("UpdatedCinemaDiscounts")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CinemaInfoEntity");

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("MovieFormatInfoEntity");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.CinemaInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Creator")
                        .WithMany("CreatedCinemas")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Deleter")
                        .WithMany("DeletedCinemas")
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "manager")
                        .WithMany("ManagedCinemas")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Updater")
                        .WithMany("UpdatedCinemas")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("Updater");

                    b.Navigation("manager");
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.CinemaSurchargeInfosEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.CinemaInfos.CinemaInfoEntity", "CinemaInfoEntity")
                        .WithMany("CinemaSurchargeInfosEntity")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Creator")
                        .WithMany("CreatedCinemaSurchargeInfos")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Deleter")
                        .WithMany("DeletedCinemaSurchargeInfos")
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.MovieInfos.MovieFormatInfoEntity", "MovieFormatInfoEntity")
                        .WithMany("cinema_surcharge_infos_entities")
                        .HasForeignKey("MovieFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Updater")
                        .WithMany("UpdatedCinemaSurchargeInfos")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.UserInfos.UserSegmentsInfoEntity", "UserSegmentsInfoEntity")
                        .WithMany("CinemaSurchargeInfosEntity")
                        .HasForeignKey("UserSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaInfoEntity");

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("MovieFormatInfoEntity");

                    b.Navigation("Updater");

                    b.Navigation("UserSegmentsInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.SeatsInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.CinemaInfos.AuditoriumInfoEntities", "AuditoriumInfoEntities")
                        .WithMany("SeatsInfoEntity")
                        .HasForeignKey("AuditoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditoriumInfoEntities");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieFormatInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Creator")
                        .WithMany("CreatedMovieFormats")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Deleter")
                        .WithMany("DeletedMovieFormats")
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Updater")
                        .WithMany("UpdatedMovieFormats")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieGenreMovieInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.MovieInfos.MovieGenreInfoEntity", "MovieGenreInfoEntity")
                        .WithMany("MovieGenreMovieInfoEntity")
                        .HasForeignKey("MovieGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.MovieInfos.MovieInfoEntity", "movie_info_entity")
                        .WithMany("MovieGenreMovieInfoEntity")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieGenreInfoEntity");

                    b.Navigation("movie_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Creator")
                        .WithMany("CreatedMovieInfos")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Deleter")
                        .WithMany("DeletedMovieInfos")
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Manager")
                        .WithMany("ManagedMovieInfos")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.MovieInfos.movieRequiredAgeEntity", "MovieRequiredAgeEntity")
                        .WithMany("movie_info_entity")
                        .HasForeignKey("MovieRequiredAgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Updater")
                        .WithMany("UpdatedMovieInfos")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("Manager");

                    b.Navigation("MovieRequiredAgeEntity");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieScheduleInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.CinemaInfos.AuditoriumInfoEntities", "AuditoriumInfoEntities")
                        .WithMany("MovieScheduleInfoEntity")
                        .HasForeignKey("AuditoriumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Creator")
                        .WithMany("CreatedSchedules")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Deleter")
                        .WithMany("DeletedSchedules")
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Entities.MovieInfos.MovieFormatInfoEntity", "MovieFormatInfoEntity")
                        .WithMany("movie_schedule_info_entities")
                        .HasForeignKey("MovieFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.MovieInfos.MovieInfoEntity", "movie_info_entity")
                        .WithMany("MovieScheduleInfoEntity")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "Updater")
                        .WithMany("UpdatedSchedules")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AuditoriumInfoEntities");

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("MovieFormatInfoEntity");

                    b.Navigation("Updater");

                    b.Navigation("movie_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.movieFormatMovieInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.MovieInfos.MovieFormatInfoEntity", "MovieFormatInfoEntity")
                        .WithMany("movieFormatMovieInfoEntities")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.MovieInfos.MovieInfoEntity", "MovieInfoEntity")
                        .WithMany("MovieFormatMovieInfoEntity")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MovieFormatInfoEntity");

                    b.Navigation("MovieInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.OrderDetailsInfo", b =>
                {
                    b.HasOne("DataAccess.Entities.MovieInfos.MovieScheduleInfoEntity", "MovieScheduleInfoEntity")
                        .WithMany("OrderDetailsInfos")
                        .HasForeignKey("MovieScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.OrderInfoEntity", "OrderInfoEntity")
                        .WithMany("OrderDetailsInfo")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MovieScheduleInfoEntity");

                    b.Navigation("OrderInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.OrderInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "UserInfoEntity")
                        .WithMany("OrderInfoEntity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UserInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.UserProfileEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "UserInfoEntity")
                        .WithOne("UserProfileEntity")
                        .HasForeignKey("DataAccess.Entities.UserInfos.UserProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.UserRoleInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.UserInfos.RoleListInfoEntity", "RoleListInfoEntity")
                        .WithMany("UserRoleInfoEntity")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.UserInfos.UserInfoEntity", "UserInfoEntity")
                        .WithMany("UserRoleInfoEntity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleListInfoEntity");

                    b.Navigation("UserInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.Vouchers.VoucherInfoEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.UserInfos.RoleListInfoEntity", "RoleListInfoEntity")
                        .WithMany("VoucherInfoEntity")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleListInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.AuditoriumInfoEntities", b =>
                {
                    b.Navigation("MovieScheduleInfoEntity");

                    b.Navigation("SeatsInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.CinemaInfos.CinemaInfoEntity", b =>
                {
                    b.Navigation("AuditoriumInfoEntities");

                    b.Navigation("CinemaDiscountInfoEntity");

                    b.Navigation("CinemaSurchargeInfosEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieFormatInfoEntity", b =>
                {
                    b.Navigation("auditorium_info_entities");

                    b.Navigation("cinema_discount_info_entities");

                    b.Navigation("cinema_surcharge_infos_entities");

                    b.Navigation("movieFormatMovieInfoEntities");

                    b.Navigation("movie_schedule_info_entities");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieGenreInfoEntity", b =>
                {
                    b.Navigation("MovieGenreMovieInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieInfoEntity", b =>
                {
                    b.Navigation("MovieFormatMovieInfoEntity");

                    b.Navigation("MovieGenreMovieInfoEntity");

                    b.Navigation("MovieScheduleInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.MovieScheduleInfoEntity", b =>
                {
                    b.Navigation("OrderDetailsInfos");
                });

            modelBuilder.Entity("DataAccess.Entities.MovieInfos.movieRequiredAgeEntity", b =>
                {
                    b.Navigation("movie_info_entity");
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.OrderInfoEntity", b =>
                {
                    b.Navigation("OrderDetailsInfo");
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.RoleListInfoEntity", b =>
                {
                    b.Navigation("UserRoleInfoEntity");

                    b.Navigation("VoucherInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.UserInfoEntity", b =>
                {
                    b.Navigation("CreatedAuditoriums");

                    b.Navigation("CreatedCinemaDiscounts");

                    b.Navigation("CreatedCinemaSurchargeInfos");

                    b.Navigation("CreatedCinemas");

                    b.Navigation("CreatedMovieFormats");

                    b.Navigation("CreatedMovieInfos");

                    b.Navigation("CreatedSchedules");

                    b.Navigation("DeletedAuditoriums");

                    b.Navigation("DeletedCinemaDiscounts");

                    b.Navigation("DeletedCinemaSurchargeInfos");

                    b.Navigation("DeletedCinemas");

                    b.Navigation("DeletedMovieFormats");

                    b.Navigation("DeletedMovieInfos");

                    b.Navigation("DeletedSchedules");

                    b.Navigation("ManagedCinemas");

                    b.Navigation("ManagedMovieInfos");

                    b.Navigation("OrderInfoEntity");

                    b.Navigation("UpdatedAuditoriums");

                    b.Navigation("UpdatedCinemaDiscounts");

                    b.Navigation("UpdatedCinemaSurchargeInfos");

                    b.Navigation("UpdatedCinemas");

                    b.Navigation("UpdatedMovieFormats");

                    b.Navigation("UpdatedMovieInfos");

                    b.Navigation("UpdatedSchedules");

                    b.Navigation("UserProfileEntity")
                        .IsRequired();

                    b.Navigation("UserRoleInfoEntity");
                });

            modelBuilder.Entity("DataAccess.Entities.UserInfos.UserSegmentsInfoEntity", b =>
                {
                    b.Navigation("CinemaSurchargeInfosEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
