SET DEFINE OFF
SET SERVEROUTPUT ON

PROMPT === Running 01_schema.sql ===
CREATE TABLE NGUOI_DUNG (
  MA_ND NUMBER PRIMARY KEY,
  HO_TEN VARCHAR2(120 CHAR) NOT NULL,
  EMAIL VARCHAR2(255 CHAR) NOT NULL UNIQUE,
  SO_DT VARCHAR2(20 CHAR),
  NGAY_SINH DATE NOT NULL,
  VAI_TRO VARCHAR2(15 CHAR) DEFAULT 'KHACH' NOT NULL,
  TRANG_THAI VARCHAR2(15 CHAR) DEFAULT 'HOAT_DONG' NOT NULL,
  NGAY_TAO DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT CK_ND_ROLE CHECK (VAI_TRO IN ('KHACH', 'NHAN_VIEN', 'QUAN_LY')),
  CONSTRAINT CK_ND_STATUS CHECK (TRANG_THAI IN ('HOAT_DONG', 'KHOA'))
);

CREATE TABLE RAP (
  MA_RAP NUMBER PRIMARY KEY,
  TEN_RAP VARCHAR2(150 CHAR) NOT NULL,
  DIA_CHI VARCHAR2(255 CHAR) NOT NULL,
  TRANG_THAI VARCHAR2(15 CHAR) DEFAULT 'HOAT_DONG' NOT NULL,
  CONSTRAINT CK_RAP_STATUS CHECK (TRANG_THAI IN ('HOAT_DONG', 'NGUNG'))
);

CREATE TABLE PHONG_CHIEU (
  MA_PHONG NUMBER PRIMARY KEY,
  MA_RAP NUMBER NOT NULL,
  TEN_PHONG VARCHAR2(80 CHAR) NOT NULL,
  SO_HANG NUMBER(3) NOT NULL,
  SO_COT NUMBER(3) NOT NULL,
  TRANG_THAI VARCHAR2(15 CHAR) DEFAULT 'HOAT_DONG' NOT NULL,
  CONSTRAINT FK_PHONG_RAP FOREIGN KEY (MA_RAP) REFERENCES RAP(MA_RAP),
  CONSTRAINT UQ_PHONG_TEN UNIQUE (MA_RAP, TEN_PHONG),
  CONSTRAINT CK_PHONG_SIZE CHECK (SO_HANG > 0 AND SO_COT > 0),
  CONSTRAINT CK_PHONG_STATUS CHECK (TRANG_THAI IN ('HOAT_DONG', 'BAO_TRI'))
);

CREATE TABLE GHE (
  MA_GHE NUMBER PRIMARY KEY,
  MA_PHONG NUMBER NOT NULL,
  HANG_GHE VARCHAR2(3 CHAR) NOT NULL,
  SO_GHE NUMBER(3) NOT NULL,
  LOAI_GHE VARCHAR2(15 CHAR) DEFAULT 'THUONG' NOT NULL,
  HE_SO_GIA NUMBER(4,2) DEFAULT 1 NOT NULL,
  CONSTRAINT FK_GHE_PHONG FOREIGN KEY (MA_PHONG) REFERENCES PHONG_CHIEU(MA_PHONG),
  CONSTRAINT UQ_GHE_VI_TRI UNIQUE (MA_PHONG, HANG_GHE, SO_GHE),
  CONSTRAINT CK_GHE_TYPE CHECK (LOAI_GHE IN ('THUONG', 'VIP', 'DOI')),
  CONSTRAINT CK_GHE_HE_SO CHECK (HE_SO_GIA > 0)
);

CREATE TABLE THE_LOAI (
  MA_TL NUMBER PRIMARY KEY,
  TEN_TL VARCHAR2(80 CHAR) NOT NULL UNIQUE
);

CREATE TABLE PHIM (
  MA_PHIM NUMBER PRIMARY KEY,
  TEN_PHIM VARCHAR2(255 CHAR) NOT NULL,
  THOI_LUONG NUMBER(4) NOT NULL,
  GIOI_HAN_TUOI NUMBER(2) DEFAULT 0 NOT NULL,
  NGAY_KHOI_CHIEU DATE,
  TRANG_THAI VARCHAR2(15 CHAR) DEFAULT 'DANG_CHIEU' NOT NULL,
  CONSTRAINT CK_PHIM_DURATION CHECK (THOI_LUONG > 0),
  CONSTRAINT CK_PHIM_AGE CHECK (GIOI_HAN_TUOI BETWEEN 0 AND 21),
  CONSTRAINT CK_PHIM_STATUS CHECK (TRANG_THAI IN ('SAP_CHIEU', 'DANG_CHIEU', 'NGUNG_CHIEU'))
);

CREATE TABLE PHIM_THE_LOAI (
  MA_PHIM NUMBER NOT NULL,
  MA_TL NUMBER NOT NULL,
  CONSTRAINT PK_PHIM_THE_LOAI PRIMARY KEY (MA_PHIM, MA_TL),
  CONSTRAINT FK_PTL_PHIM FOREIGN KEY (MA_PHIM) REFERENCES PHIM(MA_PHIM),
  CONSTRAINT FK_PTL_THE_LOAI FOREIGN KEY (MA_TL) REFERENCES THE_LOAI(MA_TL)
);

CREATE TABLE DINH_DANG (
  MA_DD NUMBER PRIMARY KEY,
  TEN_DD VARCHAR2(50 CHAR) NOT NULL UNIQUE
);

CREATE TABLE LICH_CHIEU (
  MA_LC NUMBER PRIMARY KEY,
  MA_PHIM NUMBER NOT NULL,
  MA_PHONG NUMBER NOT NULL,
  MA_DD NUMBER NOT NULL,
  TG_BAT_DAU DATE NOT NULL,
  TG_KET_THUC DATE NOT NULL,
  GIA_CO_BAN NUMBER(12,2) NOT NULL,
  TRANG_THAI VARCHAR2(15 CHAR) DEFAULT 'DANG_MO' NOT NULL,
  CONSTRAINT FK_LC_PHIM FOREIGN KEY (MA_PHIM) REFERENCES PHIM(MA_PHIM),
  CONSTRAINT FK_LC_PHONG FOREIGN KEY (MA_PHONG) REFERENCES PHONG_CHIEU(MA_PHONG),
  CONSTRAINT FK_LC_DD FOREIGN KEY (MA_DD) REFERENCES DINH_DANG(MA_DD),
  CONSTRAINT CK_LC_TIME CHECK (TG_KET_THUC > TG_BAT_DAU),
  CONSTRAINT CK_LC_PRICE CHECK (GIA_CO_BAN > 0),
  CONSTRAINT CK_LC_STATUS CHECK (TRANG_THAI IN ('DANG_MO', 'DA_HUY', 'DA_KET_THUC'))
);

CREATE TABLE DON_DAT (
  MA_DON NUMBER PRIMARY KEY,
  MA_BOOKING VARCHAR2(20 CHAR) NOT NULL UNIQUE,
  MA_KHACH NUMBER NOT NULL,
  MA_NV NUMBER,
  MA_LC NUMBER NOT NULL,
  NGAY_DAT DATE DEFAULT SYSDATE NOT NULL,
  SO_LUONG NUMBER(3) DEFAULT 0 NOT NULL,
  TONG_TIEN NUMBER(12,2) DEFAULT 0 NOT NULL,
  PHUONG_THUC_TT VARCHAR2(20 CHAR),
  TRANG_THAI VARCHAR2(20 CHAR) DEFAULT 'CHO_TT' NOT NULL,
  CONSTRAINT FK_DON_KHACH FOREIGN KEY (MA_KHACH) REFERENCES NGUOI_DUNG(MA_ND),
  CONSTRAINT FK_DON_NV FOREIGN KEY (MA_NV) REFERENCES NGUOI_DUNG(MA_ND),
  CONSTRAINT FK_DON_LC FOREIGN KEY (MA_LC) REFERENCES LICH_CHIEU(MA_LC),
  CONSTRAINT CK_DON_QTY CHECK (SO_LUONG BETWEEN 0 AND 10),
  CONSTRAINT CK_DON_TOTAL CHECK (TONG_TIEN >= 0),
  CONSTRAINT CK_DON_STATUS CHECK (TRANG_THAI IN ('CHO_TT', 'DA_THANH_TOAN', 'DA_HUY', 'DA_HOAN', 'DA_SU_DUNG'))
);

CREATE TABLE CHI_TIET_VE (
  MA_CTV NUMBER PRIMARY KEY,
  MA_DON NUMBER NOT NULL,
  MA_GHE NUMBER NOT NULL,
  DON_GIA NUMBER(12,2) NOT NULL,
  GHE_HIEU_LUC NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT FK_CTV_DON FOREIGN KEY (MA_DON) REFERENCES DON_DAT(MA_DON),
  CONSTRAINT FK_CTV_GHE FOREIGN KEY (MA_GHE) REFERENCES GHE(MA_GHE),
  CONSTRAINT UQ_CTV_GHE_ACTIVE UNIQUE (MA_DON, MA_GHE),
  CONSTRAINT CK_CTV_PRICE CHECK (DON_GIA > 0),
  CONSTRAINT CK_CTV_ACTIVE CHECK (GHE_HIEU_LUC IN (0, 1))
);

CREATE UNIQUE INDEX UX_CTV_LC_GHE_ACTIVE ON CHI_TIET_VE (
  CASE WHEN GHE_HIEU_LUC = 1 THEN MA_GHE END,
  CASE WHEN GHE_HIEU_LUC = 1 THEN MA_DON END
);

-- Seat availability across schedules is enforced by a dedicated reservation table.
CREATE TABLE GHE_DA_DAT (
  MA_LC NUMBER NOT NULL,
  MA_GHE NUMBER NOT NULL,
  MA_DON NUMBER NOT NULL,
  CONSTRAINT PK_GHE_DA_DAT PRIMARY KEY (MA_LC, MA_GHE),
  CONSTRAINT FK_GDD_LC FOREIGN KEY (MA_LC) REFERENCES LICH_CHIEU(MA_LC),
  CONSTRAINT FK_GDD_GHE FOREIGN KEY (MA_GHE) REFERENCES GHE(MA_GHE),
  CONSTRAINT FK_GDD_DON FOREIGN KEY (MA_DON) REFERENCES DON_DAT(MA_DON)
);

PROMPT === Running 02_sequences_triggers.sql ===
CREATE SEQUENCE SEQ_NGUOI_DUNG START WITH 1;
CREATE SEQUENCE SEQ_RAP START WITH 1;
CREATE SEQUENCE SEQ_PHONG_CHIEU START WITH 1;
CREATE SEQUENCE SEQ_GHE START WITH 1;
CREATE SEQUENCE SEQ_THE_LOAI START WITH 1;
CREATE SEQUENCE SEQ_PHIM START WITH 1;
CREATE SEQUENCE SEQ_DINH_DANG START WITH 1;
CREATE SEQUENCE SEQ_LICH_CHIEU START WITH 1;
CREATE SEQUENCE SEQ_DON_DAT START WITH 1;
CREATE SEQUENCE SEQ_CHI_TIET_VE START WITH 1;

CREATE OR REPLACE TRIGGER BI_NGUOI_DUNG_ID BEFORE INSERT ON NGUOI_DUNG FOR EACH ROW BEGIN IF :NEW.MA_ND IS NULL THEN :NEW.MA_ND := SEQ_NGUOI_DUNG.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER BI_RAP_ID BEFORE INSERT ON RAP FOR EACH ROW BEGIN IF :NEW.MA_RAP IS NULL THEN :NEW.MA_RAP := SEQ_RAP.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER BI_PHONG_CHIEU_ID BEFORE INSERT ON PHONG_CHIEU FOR EACH ROW BEGIN IF :NEW.MA_PHONG IS NULL THEN :NEW.MA_PHONG := SEQ_PHONG_CHIEU.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER BI_GHE_ID BEFORE INSERT ON GHE FOR EACH ROW BEGIN IF :NEW.MA_GHE IS NULL THEN :NEW.MA_GHE := SEQ_GHE.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER BI_THE_LOAI_ID BEFORE INSERT ON THE_LOAI FOR EACH ROW BEGIN IF :NEW.MA_TL IS NULL THEN :NEW.MA_TL := SEQ_THE_LOAI.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER BI_PHIM_ID BEFORE INSERT ON PHIM FOR EACH ROW BEGIN IF :NEW.MA_PHIM IS NULL THEN :NEW.MA_PHIM := SEQ_PHIM.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER BI_DINH_DANG_ID BEFORE INSERT ON DINH_DANG FOR EACH ROW BEGIN IF :NEW.MA_DD IS NULL THEN :NEW.MA_DD := SEQ_DINH_DANG.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER BI_LICH_CHIEU_ID BEFORE INSERT ON LICH_CHIEU FOR EACH ROW BEGIN IF :NEW.MA_LC IS NULL THEN :NEW.MA_LC := SEQ_LICH_CHIEU.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER BI_DON_DAT_ID BEFORE INSERT ON DON_DAT FOR EACH ROW BEGIN IF :NEW.MA_DON IS NULL THEN :NEW.MA_DON := SEQ_DON_DAT.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER BI_CHI_TIET_VE_ID BEFORE INSERT ON CHI_TIET_VE FOR EACH ROW BEGIN IF :NEW.MA_CTV IS NULL THEN :NEW.MA_CTV := SEQ_CHI_TIET_VE.NEXTVAL; END IF; END;
/

CREATE OR REPLACE TRIGGER BIU_NGUOI_DUNG_TUOI
  BEFORE INSERT OR UPDATE OF NGAY_SINH, VAI_TRO ON NGUOI_DUNG
  FOR EACH ROW
BEGIN
  IF (:NEW.VAI_TRO = 'KHACH' AND ADD_MONTHS(:NEW.NGAY_SINH, 16 * 12) > TRUNC(SYSDATE))
     OR (:NEW.VAI_TRO IN ('NHAN_VIEN', 'QUAN_LY') AND ADD_MONTHS(:NEW.NGAY_SINH, 18 * 12) > TRUNC(SYSDATE)) THEN
    RAISE_APPLICATION_ERROR(-20001, 'Nguoi dung chua du tuoi theo vai tro.');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER BIU_LICH_CHIEU_KHONG_TRUNG
  BEFORE INSERT OR UPDATE OF MA_PHONG, TG_BAT_DAU, TG_KET_THUC, TRANG_THAI ON LICH_CHIEU
  FOR EACH ROW
DECLARE
  v_count NUMBER;
BEGIN
  IF :NEW.TRANG_THAI <> 'DA_HUY' THEN
    IF :NEW.TG_BAT_DAU < SYSDATE THEN
      RAISE_APPLICATION_ERROR(-20002, 'Lich chieu phai bat dau trong tuong lai.');
    END IF;
    SELECT COUNT(*) INTO v_count
    FROM LICH_CHIEU lc
    WHERE lc.MA_PHONG = :NEW.MA_PHONG
      AND lc.TRANG_THAI <> 'DA_HUY'
      AND lc.MA_LC <> NVL(:NEW.MA_LC, -1)
      AND :NEW.TG_BAT_DAU < lc.TG_KET_THUC + 15 / 1440
      AND :NEW.TG_KET_THUC + 15 / 1440 > lc.TG_BAT_DAU;
    IF v_count > 0 THEN
      RAISE_APPLICATION_ERROR(-20003, 'Phong chieu da co lich trung hoac chua du 15 phut don phong.');
    END IF;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER BIU_DON_DAT_STATUS
  BEFORE INSERT OR UPDATE OF TRANG_THAI ON DON_DAT
  FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.TRANG_THAI IS NULL THEN
    :NEW.TRANG_THAI := 'CHO_TT';
  ELSIF UPDATING THEN
    IF :OLD.TRANG_THAI IN ('DA_HUY', 'DA_HOAN', 'DA_SU_DUNG') THEN
      RAISE_APPLICATION_ERROR(-20004, 'Don o trang thai cuoi khong duoc thay doi.');
    ELSIF :OLD.TRANG_THAI = 'CHO_TT' AND :NEW.TRANG_THAI NOT IN ('CHO_TT', 'DA_THANH_TOAN', 'DA_HUY') THEN
      RAISE_APPLICATION_ERROR(-20005, 'Chuyen trang thai don khong hop le.');
    ELSIF :OLD.TRANG_THAI = 'DA_THANH_TOAN' AND :NEW.TRANG_THAI NOT IN ('DA_THANH_TOAN', 'DA_HUY', 'DA_HOAN', 'DA_SU_DUNG') THEN
      RAISE_APPLICATION_ERROR(-20005, 'Chuyen trang thai don khong hop le.');
    END IF;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AU_DON_DAT_GIAI_PHONG_GHE
  AFTER UPDATE OF TRANG_THAI ON DON_DAT
  FOR EACH ROW
BEGIN
  IF :NEW.TRANG_THAI IN ('DA_HUY', 'DA_HOAN') THEN
    UPDATE CHI_TIET_VE SET GHE_HIEU_LUC = 0 WHERE MA_DON = :NEW.MA_DON;
    DELETE FROM GHE_DA_DAT WHERE MA_DON = :NEW.MA_DON;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER BIU_CHI_TIET_VE_GHE
  BEFORE INSERT OR UPDATE OF MA_GHE ON CHI_TIET_VE
  FOR EACH ROW
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM DON_DAT d JOIN LICH_CHIEU lc ON lc.MA_LC = d.MA_LC JOIN GHE g ON g.MA_GHE = :NEW.MA_GHE
  WHERE d.MA_DON = :NEW.MA_DON AND g.MA_PHONG = lc.MA_PHONG;
  IF v_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20006, 'Ghe khong thuoc phong cua lich chieu.');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AI_CHI_TIET_VE_GIU_GHE
  AFTER INSERT ON CHI_TIET_VE
  FOR EACH ROW
DECLARE
  v_ma_lc NUMBER;
BEGIN
  IF :NEW.GHE_HIEU_LUC = 1 THEN
    SELECT MA_LC INTO v_ma_lc FROM DON_DAT WHERE MA_DON = :NEW.MA_DON;
    INSERT INTO GHE_DA_DAT (MA_LC, MA_GHE, MA_DON) VALUES (v_ma_lc, :NEW.MA_GHE, :NEW.MA_DON);
  END IF;
END;
/

PROMPT === Running 03_functions_procedures.sql ===
CREATE OR REPLACE FUNCTION F_TINH_GIA (p_ma_lc IN NUMBER, p_ma_ghe IN NUMBER)
RETURN NUMBER
IS
  v_gia NUMBER(12,2);
BEGIN
  SELECT lc.GIA_CO_BAN * g.HE_SO_GIA INTO v_gia
  FROM LICH_CHIEU lc JOIN GHE g ON g.MA_PHONG = lc.MA_PHONG
  WHERE lc.MA_LC = p_ma_lc AND g.MA_GHE = p_ma_ghe;
  RETURN v_gia;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20010, 'Khong tim thay ghe trong lich chieu.');
END;
/

CREATE OR REPLACE PROCEDURE P_DAT_VE (
  p_ma_khach IN NUMBER,
  p_ma_nv IN NUMBER,
  p_ma_lc IN NUMBER,
  p_ds_ghe IN SYS.ODCINUMBERLIST,
  p_pt_thanh_toan IN VARCHAR2,
  p_ma_don OUT NUMBER
)
IS
  v_ma_phong NUMBER;
  v_status VARCHAR2(15);
  v_count NUMBER;
  v_total NUMBER(12,2) := 0;
  v_gia NUMBER(12,2);
BEGIN
  IF p_ds_ghe IS NULL OR p_ds_ghe.COUNT = 0 OR p_ds_ghe.COUNT > 10 THEN
    RAISE_APPLICATION_ERROR(-20011, 'Mot don chi duoc dat tu 1 den 10 ghe.');
  END IF;
  SELECT MA_PHONG, TRANG_THAI INTO v_ma_phong, v_status FROM LICH_CHIEU WHERE MA_LC = p_ma_lc FOR UPDATE;
  IF v_status <> 'DANG_MO' THEN RAISE_APPLICATION_ERROR(-20012, 'Lich chieu khong con mo ban ve.'); END IF;
  SELECT COUNT(DISTINCT COLUMN_VALUE) INTO v_count FROM TABLE(p_ds_ghe);
  IF v_count <> p_ds_ghe.COUNT THEN RAISE_APPLICATION_ERROR(-20013, 'Danh sach ghe co gia tri trung.'); END IF;
  SELECT COUNT(*) INTO v_count FROM GHE WHERE MA_PHONG = v_ma_phong AND MA_GHE IN (SELECT COLUMN_VALUE FROM TABLE(p_ds_ghe));
  IF v_count <> p_ds_ghe.COUNT THEN RAISE_APPLICATION_ERROR(-20014, 'Co ghe khong thuoc phong chieu.'); END IF;
  SELECT COUNT(*) INTO v_count FROM GHE_DA_DAT WHERE MA_LC = p_ma_lc AND MA_GHE IN (SELECT COLUMN_VALUE FROM TABLE(p_ds_ghe));
  IF v_count > 0 THEN RAISE_APPLICATION_ERROR(-20015, 'Mot hoac nhieu ghe da duoc dat.'); END IF;

  p_ma_don := SEQ_DON_DAT.NEXTVAL;
  INSERT INTO DON_DAT (MA_DON, MA_BOOKING, MA_KHACH, MA_NV, MA_LC, SO_LUONG, TONG_TIEN, PHUONG_THUC_TT, TRANG_THAI)
  VALUES (p_ma_don, 'BK' || LPAD(p_ma_don, 8, '0'), p_ma_khach, p_ma_nv, p_ma_lc, p_ds_ghe.COUNT, 0, p_pt_thanh_toan, 'CHO_TT');
  FOR i IN 1 .. p_ds_ghe.COUNT LOOP
    v_gia := F_TINH_GIA(p_ma_lc, p_ds_ghe(i));
    INSERT INTO CHI_TIET_VE (MA_CTV, MA_DON, MA_GHE, DON_GIA) VALUES (SEQ_CHI_TIET_VE.NEXTVAL, p_ma_don, p_ds_ghe(i), v_gia);
    v_total := v_total + v_gia;
  END LOOP;
  UPDATE DON_DAT SET TONG_TIEN = v_total WHERE MA_DON = p_ma_don;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE P_THANH_TOAN (p_ma_don IN NUMBER, p_pt_thanh_toan IN VARCHAR2, p_trang_thai OUT VARCHAR2)
IS
BEGIN
  UPDATE DON_DAT SET TRANG_THAI = 'DA_THANH_TOAN', PHUONG_THUC_TT = p_pt_thanh_toan
  WHERE MA_DON = p_ma_don AND TRANG_THAI = 'CHO_TT';
  IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20016, 'Don khong ton tai hoac khong the thanh toan.'); END IF;
  p_trang_thai := 'DA_THANH_TOAN'; COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE P_HUY_DON (p_ma_don IN NUMBER, p_ly_do IN VARCHAR2, p_trang_thai OUT VARCHAR2)
IS
  v_status VARCHAR2(20);
  v_start DATE;
BEGIN
  SELECT d.TRANG_THAI, lc.TG_BAT_DAU INTO v_status, v_start FROM DON_DAT d JOIN LICH_CHIEU lc ON lc.MA_LC = d.MA_LC WHERE d.MA_DON = p_ma_don FOR UPDATE;
  IF v_status = 'CHO_TT' OR (v_status = 'DA_THANH_TOAN' AND v_start > SYSDATE + 2 / 24) THEN
    UPDATE DON_DAT SET TRANG_THAI = 'DA_HUY' WHERE MA_DON = p_ma_don;
    p_trang_thai := 'DA_HUY'; COMMIT;
  ELSE RAISE_APPLICATION_ERROR(-20017, 'Don khong du dieu kien huy.'); END IF;
END;
/

CREATE OR REPLACE PROCEDURE P_HUY_DON_QUA_HAN (p_so_don_huy OUT NUMBER)
IS
BEGIN
  UPDATE DON_DAT SET TRANG_THAI = 'DA_HUY'
  WHERE TRANG_THAI = 'CHO_TT' AND NGAY_DAT < SYSDATE - 10 / 1440;
  p_so_don_huy := SQL%ROWCOUNT; COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE P_THEM_LICH_CHIEU (
  p_ma_phim IN NUMBER, p_ma_phong IN NUMBER, p_ma_dd IN NUMBER,
  p_tg_bat_dau IN DATE, p_tg_ket_thuc IN DATE, p_gia_co_ban IN NUMBER, p_ma_lc OUT NUMBER
)
IS
BEGIN
  p_ma_lc := SEQ_LICH_CHIEU.NEXTVAL;
  INSERT INTO LICH_CHIEU (MA_LC, MA_PHIM, MA_PHONG, MA_DD, TG_BAT_DAU, TG_KET_THUC, GIA_CO_BAN)
  VALUES (p_ma_lc, p_ma_phim, p_ma_phong, p_ma_dd, p_tg_bat_dau, p_tg_ket_thuc, p_gia_co_ban);
  COMMIT;
END;
/

PROMPT === Running 04_views_reports.sql ===
CREATE OR REPLACE VIEW V_DOANH_THU_NGAY AS
SELECT TRUNC(NGAY_DAT) AS NGAY, COUNT(*) AS SO_DON, SUM(TONG_TIEN) AS DOANH_THU
FROM DON_DAT
WHERE TRANG_THAI IN ('DA_THANH_TOAN', 'DA_SU_DUNG')
GROUP BY TRUNC(NGAY_DAT);

CREATE OR REPLACE VIEW V_GHE_TRONG AS
SELECT lc.MA_LC, lc.TG_BAT_DAU, p.TEN_PHIM, pc.TEN_PHONG, g.MA_GHE, g.HANG_GHE, g.SO_GHE, g.LOAI_GHE
FROM LICH_CHIEU lc
JOIN PHIM p ON p.MA_PHIM = lc.MA_PHIM
JOIN PHONG_CHIEU pc ON pc.MA_PHONG = lc.MA_PHONG
JOIN GHE g ON g.MA_PHONG = pc.MA_PHONG
WHERE lc.TRANG_THAI = 'DANG_MO'
  AND NOT EXISTS (SELECT 1 FROM GHE_DA_DAT gd WHERE gd.MA_LC = lc.MA_LC AND gd.MA_GHE = g.MA_GHE);

CREATE OR REPLACE VIEW V_LICH_CHIEU_HOM_NAY AS
SELECT lc.MA_LC, p.TEN_PHIM, r.TEN_RAP, pc.TEN_PHONG, dd.TEN_DD, lc.TG_BAT_DAU, lc.TG_KET_THUC, lc.GIA_CO_BAN
FROM LICH_CHIEU lc
JOIN PHIM p ON p.MA_PHIM = lc.MA_PHIM
JOIN PHONG_CHIEU pc ON pc.MA_PHONG = lc.MA_PHONG
JOIN RAP r ON r.MA_RAP = pc.MA_RAP
JOIN DINH_DANG dd ON dd.MA_DD = lc.MA_DD
WHERE TRUNC(lc.TG_BAT_DAU) = TRUNC(SYSDATE) AND lc.TRANG_THAI = 'DANG_MO';

CREATE OR REPLACE PROCEDURE P_BAO_CAO_DOANH_THU (p_tu_ngay IN DATE, p_den_ngay IN DATE, p_ket_qua OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN p_ket_qua FOR
    SELECT * FROM V_DOANH_THU_NGAY WHERE NGAY BETWEEN TRUNC(p_tu_ngay) AND TRUNC(p_den_ngay) ORDER BY NGAY;
END;
/

CREATE OR REPLACE PROCEDURE P_BAO_CAO_GHE_TRONG (p_ma_lc IN NUMBER, p_ket_qua OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN p_ket_qua FOR SELECT * FROM V_GHE_TRONG WHERE MA_LC = p_ma_lc ORDER BY HANG_GHE, SO_GHE;
END;
/

PROMPT === Running 05_roles_grants.sql ===
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE R_ADMIN_HE_THONG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1921 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE R_QUAN_LY_RAP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1921 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE R_QUAN_LY_PHIM'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1921 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE R_PHONG_VAN_HANH'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1921 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE ROLE R_THU_NGAN'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1921 THEN RAISE; END IF; END;
/

-- 1. Admin he thong: toan quyen tren CSDL bai tap.
GRANT SELECT, INSERT, UPDATE, DELETE ON NGUOI_DUNG TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON RAP TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON PHONG_CHIEU TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON GHE TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON THE_LOAI TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON PHIM TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON PHIM_THE_LOAI TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON DINH_DANG TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON LICH_CHIEU TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON DON_DAT TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON CHI_TIET_VE TO R_ADMIN_HE_THONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON GHE_DA_DAT TO R_ADMIN_HE_THONG;
GRANT SELECT ON V_DOANH_THU_NGAY TO R_ADMIN_HE_THONG;
GRANT SELECT ON V_GHE_TRONG TO R_ADMIN_HE_THONG;
GRANT SELECT ON V_LICH_CHIEU_HOM_NAY TO R_ADMIN_HE_THONG;
GRANT EXECUTE ON P_DAT_VE TO R_ADMIN_HE_THONG;
GRANT EXECUTE ON P_THANH_TOAN TO R_ADMIN_HE_THONG;
GRANT EXECUTE ON P_HUY_DON TO R_ADMIN_HE_THONG;
GRANT EXECUTE ON P_HUY_DON_QUA_HAN TO R_ADMIN_HE_THONG;
GRANT EXECUTE ON P_THEM_LICH_CHIEU TO R_ADMIN_HE_THONG;

-- 2. Quan ly rap phim: quan ly rap, phong, ghe va lich chieu.
GRANT SELECT, INSERT, UPDATE ON RAP TO R_QUAN_LY_RAP;
GRANT SELECT, INSERT, UPDATE ON PHONG_CHIEU TO R_QUAN_LY_RAP;
GRANT SELECT, INSERT, UPDATE ON GHE TO R_QUAN_LY_RAP;
GRANT SELECT ON PHIM TO R_QUAN_LY_RAP;
GRANT SELECT ON DINH_DANG TO R_QUAN_LY_RAP;
GRANT SELECT ON LICH_CHIEU TO R_QUAN_LY_RAP;
GRANT SELECT ON V_LICH_CHIEU_HOM_NAY TO R_QUAN_LY_RAP;
GRANT EXECUTE ON P_THEM_LICH_CHIEU TO R_QUAN_LY_RAP;

-- 3. Quan ly phim: quan ly danh muc va thong tin phim.
GRANT SELECT, INSERT, UPDATE ON PHIM TO R_QUAN_LY_PHIM;
GRANT SELECT, INSERT, UPDATE ON THE_LOAI TO R_QUAN_LY_PHIM;
GRANT SELECT, INSERT, UPDATE ON PHIM_THE_LOAI TO R_QUAN_LY_PHIM;
GRANT SELECT, INSERT, UPDATE ON DINH_DANG TO R_QUAN_LY_PHIM;
GRANT SELECT ON V_LICH_CHIEU_HOM_NAY TO R_QUAN_LY_PHIM;

-- 4. Phong van hanh: dat ve, thanh toan, huy don va xem bao cao.
GRANT SELECT ON LICH_CHIEU TO R_PHONG_VAN_HANH;
GRANT SELECT ON GHE TO R_PHONG_VAN_HANH;
GRANT SELECT ON V_GHE_TRONG TO R_PHONG_VAN_HANH;
GRANT SELECT ON V_LICH_CHIEU_HOM_NAY TO R_PHONG_VAN_HANH;
GRANT SELECT ON V_DOANH_THU_NGAY TO R_PHONG_VAN_HANH;
GRANT EXECUTE ON P_DAT_VE TO R_PHONG_VAN_HANH;
GRANT EXECUTE ON P_THANH_TOAN TO R_PHONG_VAN_HANH;
GRANT EXECUTE ON P_HUY_DON TO R_PHONG_VAN_HANH;
GRANT EXECUTE ON P_HUY_DON_QUA_HAN TO R_PHONG_VAN_HANH;


-- 5. Thu ngan: chi thuc hien giao dich ban ve tai quay.
GRANT SELECT ON LICH_CHIEU TO R_THU_NGAN;
GRANT SELECT ON GHE TO R_THU_NGAN;
GRANT SELECT ON V_GHE_TRONG TO R_THU_NGAN;
GRANT SELECT ON V_LICH_CHIEU_HOM_NAY TO R_THU_NGAN;
GRANT EXECUTE ON P_DAT_VE TO R_THU_NGAN;
GRANT EXECUTE ON P_THANH_TOAN TO R_THU_NGAN;
GRANT EXECUTE ON P_HUY_DON TO R_THU_NGAN;
BEGIN EXECUTE IMMEDIATE 'GRANT R_ADMIN_HE_THONG TO CINEMA_ADMIN'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1917 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT R_QUAN_LY_RAP TO CINEMA_THEATER_MGR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1917 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT R_QUAN_LY_PHIM TO CINEMA_MOVIE_MGR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1917 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT R_PHONG_VAN_HANH TO CINEMA_FACILITIES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1917 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT R_THU_NGAN TO CINEMA_CASHIER'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1917 THEN RAISE; END IF; END;
/
PROMPT === Running 06_seed_data.sql ===
INSERT INTO NGUOI_DUNG (MA_ND, HO_TEN, EMAIL, SO_DT, NGAY_SINH, VAI_TRO) VALUES (1, 'Nguyen Van An', 'an@example.com', '0901000001', DATE '1995-05-10', 'KHACH');
INSERT INTO NGUOI_DUNG (MA_ND, HO_TEN, EMAIL, SO_DT, NGAY_SINH, VAI_TRO) VALUES (2, 'Tran Thi Binh', 'binh@example.com', '0901000002', DATE '1990-08-20', 'NHAN_VIEN');
INSERT INTO RAP (MA_RAP, TEN_RAP, DIA_CHI) VALUES (1, 'Galaxy Demo', 'Quan 1, TP HCM');
INSERT INTO PHONG_CHIEU (MA_PHONG, MA_RAP, TEN_PHONG, SO_HANG, SO_COT) VALUES (1, 1, 'Phong 01', 3, 4);
INSERT INTO GHE (MA_GHE, MA_PHONG, HANG_GHE, SO_GHE, LOAI_GHE, HE_SO_GIA) VALUES (1, 1, 'A', 1, 'THUONG', 1);
INSERT INTO GHE (MA_GHE, MA_PHONG, HANG_GHE, SO_GHE, LOAI_GHE, HE_SO_GIA) VALUES (2, 1, 'A', 2, 'THUONG', 1);
INSERT INTO GHE (MA_GHE, MA_PHONG, HANG_GHE, SO_GHE, LOAI_GHE, HE_SO_GIA) VALUES (3, 1, 'A', 3, 'VIP', 1.3);
INSERT INTO GHE (MA_GHE, MA_PHONG, HANG_GHE, SO_GHE, LOAI_GHE, HE_SO_GIA) VALUES (4, 1, 'A', 4, 'VIP', 1.3);
INSERT INTO GHE (MA_GHE, MA_PHONG, HANG_GHE, SO_GHE, LOAI_GHE, HE_SO_GIA) VALUES (5, 1, 'B', 1, 'THUONG', 1);
INSERT INTO GHE (MA_GHE, MA_PHONG, HANG_GHE, SO_GHE, LOAI_GHE, HE_SO_GIA) VALUES (6, 1, 'B', 2, 'THUONG', 1);
INSERT INTO GHE (MA_GHE, MA_PHONG, HANG_GHE, SO_GHE, LOAI_GHE, HE_SO_GIA) VALUES (7, 1, 'B', 3, 'VIP', 1.3);
INSERT INTO GHE (MA_GHE, MA_PHONG, HANG_GHE, SO_GHE, LOAI_GHE, HE_SO_GIA) VALUES (8, 1, 'B', 4, 'VIP', 1.3);
INSERT INTO THE_LOAI (MA_TL, TEN_TL) VALUES (1, 'Hanh dong');
INSERT INTO PHIM (MA_PHIM, TEN_PHIM, THOI_LUONG, GIOI_HAN_TUOI, NGAY_KHOI_CHIEU) VALUES (1, 'Hanh tinh xa', 120, 13, TRUNC(SYSDATE));
INSERT INTO PHIM_THE_LOAI (MA_PHIM, MA_TL) VALUES (1, 1);
INSERT INTO DINH_DANG (MA_DD, TEN_DD) VALUES (1, '2D Phu de');
INSERT INTO LICH_CHIEU (MA_LC, MA_PHIM, MA_PHONG, MA_DD, TG_BAT_DAU, TG_KET_THUC, GIA_CO_BAN) VALUES (1, 1, 1, 1, TRUNC(SYSDATE) + 1 + 18/24, TRUNC(SYSDATE) + 1 + 20/24, 90000);
INSERT INTO DON_DAT (MA_DON, MA_BOOKING, MA_KHACH, MA_NV, MA_LC, NGAY_DAT, SO_LUONG, TONG_TIEN, PHUONG_THUC_TT, TRANG_THAI) VALUES (1, 'BK00000001', 1, 2, 1, SYSDATE, 1, 90000, 'MOMO', 'DA_THANH_TOAN');
INSERT INTO CHI_TIET_VE (MA_CTV, MA_DON, MA_GHE, DON_GIA) VALUES (1, 1, 1, 90000);

ALTER SEQUENCE SEQ_NGUOI_DUNG RESTART START WITH 3;
ALTER SEQUENCE SEQ_RAP RESTART START WITH 2;
ALTER SEQUENCE SEQ_PHONG_CHIEU RESTART START WITH 2;
ALTER SEQUENCE SEQ_GHE RESTART START WITH 9;
ALTER SEQUENCE SEQ_THE_LOAI RESTART START WITH 2;
ALTER SEQUENCE SEQ_PHIM RESTART START WITH 2;
ALTER SEQUENCE SEQ_DINH_DANG RESTART START WITH 2;
ALTER SEQUENCE SEQ_LICH_CHIEU RESTART START WITH 2;
ALTER SEQUENCE SEQ_DON_DAT RESTART START WITH 2;
ALTER SEQUENCE SEQ_CHI_TIET_VE RESTART START WITH 2;
COMMIT;

PROMPT === CINEMA_APP setup completed ===
