services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - cinema-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - cinema-network

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge
