ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  v_count NUMBER;
  PROCEDURE tao_user(p_username IN VARCHAR2, p_password IN VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = p_username;
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE USER ' || p_username || ' IDENTIFIED BY ' || p_password || ' QUOTA UNLIMITED ON USERS';
    END IF;
  END;
BEGIN
  tao_user('CINEMA_APP', 'Cinema123');
  tao_user('CINEMA_ADMIN', 'Admin123');
  tao_user('CINEMA_THEATER_MGR', 'Theater123');
  tao_user('CINEMA_MOVIE_MGR', 'Movie123');
  tao_user('CINEMA_FACILITIES', 'Facility123');
  tao_user('CINEMA_CASHIER', 'Cashier123');
END;
/

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE,
      CREATE TRIGGER, CREATE SEQUENCE, CREATE ROLE TO CINEMA_APP;
GRANT CREATE SESSION TO CINEMA_ADMIN, CINEMA_THEATER_MGR, CINEMA_MOVIE_MGR, CINEMA_FACILITIES, CINEMA_CASHIER;